# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4b88b1c9fb312d8b4123017402fbd0e47ee354b3460d42cbaba51734746b15f9c6ad86e6a4a40f8bd07d153330d46135abe23b93d7d171ef01e83faa1119064e

test:
  secret_key_base: aaa79677ab9672a8f752c863a64f6356f09061ce024dbcadc3d4f6f73d75860535707f3c6a104d5d56ef8448531ae5ce7e4f5556cb38dfab3b47ad14b8741d5d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
